import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from './components/LayoutWrapper'
import {AppProvider} from './context/AppContext'
import { Toaster } from 'react-hot-toast'
import {MotionConfig} from 'motion/react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car rental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AppProvider>
        <Toaster/>
        <LayoutWrapper>
          <MotionConfig viewport={{once: true}}>
            {children}
          </MotionConfig>
        </LayoutWrapper>
        </AppProvider>               
      </body>
    </html>
  );
}
